First task
h31/NetworksLab2018 pull request #10
Opened 2018-10-07 19:53 UTC by VakhaevIlya

2018-10-16 17:14 UTC, h31 requested changes

2018-10-16 17:14 UTC, h31 commented on tcp_template/server_linux/main.c
> +		buffer[r_size] = '\0';
Съехало форматирование.

2018-10-16 17:14 UTC, h31 commented on tcp_template/server_linux/main.c
> +    if (r_size < 0)
А если `r_size == 0`?

2018-10-16 17:14 UTC, h31 commented on tcp_template/server_linux/main.c
> +    	close(sockt);
Этого кода недостаточно для корректного завершения сервера. Клиентские сокеты остаются незакрытыми.

2018-10-16 17:15 UTC, h31 commented on tcp_template/server_linux/main.c
> +}
Не стоит без повода выкладывать бинарные файлы в Git.

2018-10-16 17:17 UTC, h31 commented
Ваш сервер не собирается. Забыли исправить CMakeLists.txt.
```
CMakeFiles/server_linux.dir/main.c.o: In function `main':
main.c:(.text+0x11a): undefined reference to `pthread_create'
collect2: error: ld returned 1 exit status
```

2018-10-18 17:25 UTC, VakhaevIlya commented on tcp_template/server_linux/main.c
> +    if (r_size < 0)
Чуть ниже в коде присутствует это условие
`if(r_size == 0)
	{	
        	puts("Client disconnect ");
        	fflush(stdout);
    	}`

2018-11-26 17:20 UTC, h31 commented
Принято.

2018-11-26 17:20 UTC, closed without merging