1st task
h31/NetworksLab2018 pull request #2
Opened 2018-09-21 19:29 UTC by radleweird

2018-10-15 17:37 UTC, h31 requested changes

2018-10-15 17:37 UTC, h31 commented on simple_tcp/client_linux/main.c
> +	signal(SIGINT, closeApp);
Хорошая идея - обработать SIGINT. Ещё было бы неплохо обработать SIGTERM, потому что именно его обычно отправляют службам.

2018-10-15 17:37 UTC, h31 commented on simple_tcp/client_linux/main.c
> +	textInputSize = 0;
Можно эти две строчки объединить в одну.

2018-10-15 17:37 UTC, h31 commented on simple_tcp/server_linux/main.c
> +pthread_mutex_t mutex;
Используйте более понятные имена переменных. Для чего именно этот мьютекс и т.п.

2018-10-15 17:37 UTC, h31 commented on simple_tcp/server_linux/main.c
> +	timeout.tv_sec = MAX_SECONDS_READ_TIMEOUT;
5 секунд - очень короткий таймаут. Исправлять не нужно, просто имейте в виду, что есть много протоколов, где соединение может висеть часами без передачи данных. Теоретически, ничего плохого произойти не должно, если вы будете в цикле вызывать read каждые 5 секунд. Просто это лишняя нагрузка, особенно на устройствах с питанием от аккумуляторов.

2018-10-15 17:37 UTC, h31 commented on simple_tcp/server_linux/main.c
> +		totalBytesCount = write(newsockfd, "I got your message", 18);
Всё отлично, только сообщения в сторону клиенту тоже могут приходить частями, так что их нужно оформить в протокол (с передачей длины сообщения).

2018-10-15 17:37 UTC, h31 commented on simple_tcp/client_linux/main.c
> +		#ifdef IMITATE_PARTLY_SENDING
Очень хорошая идея.

2018-10-15 17:37 UTC, h31 commented on simple_tcp/server_linux/main.c
> +		printf("There are some clients on the end, count = %d\r\n", totalActiveClientsCount);
Лучше не ждать завершения работы с клиентами, а принудительно закончить обмен данными с ними.

2018-11-19 16:28 UTC, h31 commented
Не вижу исправлений.

2018-11-25 18:05 UTC, radleweird commented on simple_tcp/server_linux/main.c
> +		printf("There are some clients on the end, count = %d\r\n", totalActiveClientsCount);
Как раз для этого я добавил таймайт при чтении с клиентского сокета. На этом цикле сервер может ожидать максимум 5 секунд (длительность таймаута).

2018-11-26 17:07 UTC, h31 commented
Принято

2018-11-26 17:07 UTC, closed without merging