Task 1
h31/NetworksLab2018 pull request #5
Opened 2018-09-22 02:59 UTC by MrOlolo

2018-10-16 16:26 UTC, h31 requested changes

2018-10-16 16:26 UTC, h31 commented on simple_tcp/server_linux/main.c
> +    int checkKey = 0;
Зачем нужна эта переменная?

2018-10-16 16:26 UTC, h31 commented on simple_tcp/server_linux/main.c
> +    strcat(msg, buffer + 1);
Эту же задачу можно решить и с единственным буфером, без отдельной переменной `msg`.

2018-10-16 16:26 UTC, h31 commented on simple_tcp/server_linux/main.c
> +        if (n < 0) {
А если `n == 0`?

2018-10-16 16:26 UTC, h31 commented on simple_tcp/server_linux/main.c
> +    n = read(newsockfd, buffer, 255); // recv on Windows
Почему `read` и здесь, и на 55-ой строке?

2018-10-16 16:26 UTC, h31 commented on simple_tcp/server_linux/main.c
> +            serverListening = 0;
Команда выключения сервера должна полностью его выключать, а не просто останавливать прием новых соединений. Кроме того, название запутывает, `Listening` сразу вызывает ассоциации с вызовом `listen`, а реально этот флаг влияет на вызов `accept`.

2018-10-18 22:38 UTC, MrOlolo commented on simple_tcp/server_linux/main.c
> +    n = read(newsockfd, buffer, 255); // recv on Windows
Если в строке 41 сообщение получено не полностью, то пытаемся получить недостающую часть сообщения в цикле, для этого в нем используем read и сверяем размер сообщения.

2018-11-26 17:11 UTC, h31 commented
Принято.

2018-11-26 17:11 UTC, closed without merging