Task1
h31/NetworksLab2018 pull request #6
Opened 2018-09-22 09:56 UTC by vana06

2018-10-16 16:53 UTC, h31 requested changes

2018-10-16 16:53 UTC, h31 commented on simple_tcp/client_linux/main.c
> +	char* buffer = (char*)malloc(256);
А кто потом память будет освобождать?

2018-10-16 16:53 UTC, h31 commented on simple_tcp/client_linux/main.c
> +	toSend[0] = ((messageLength >> 24) & 0xff) + '0';
Выглядит интересно, но я бы заменил этот код на вызов `snprintf`. Это надежнее и понятнее.

2018-10-16 16:53 UTC, h31 commented on simple_tcp/client_linux/main.c
> +	char *buffer = (char*)malloc(256);
Я бы заменил на `calloc`. Не факт, что сообщение будет null-terminated.

2018-10-16 16:53 UTC, h31 commented on simple_tcp/server_linux/main.c
> +	if(setsockopt(sockfd, SOL_SOCKET,(SO_REUSEPORT | SO_REUSEADDR),&(int){ 1 }, sizeof(int)) < 0){
Пожалуйста, пишите, [откуда](https://github.com/h31/NetworksLab2018/pull/4/files#diff-d60665806a7161a7d1d5f9a8ef9c878dR47) берете этот код. И см. замечание по ссылке.

2018-10-16 16:53 UTC, h31 commented on simple_tcp/server_linux/main.c
> +	toSend[0] = ((messageLength >> 24) & 0xff) + '0';
Общий код между клиентом и сервером лучше вынести в отдельный файл.

2018-10-16 16:53 UTC, h31 commented on simple_tcp/server_linux/main.c
> +		closeSocket(temp, 1, 0, "");
Если закрыть сокет в одном процессе, то в другом он останется открытым. См. [ответы](https://stackoverflow.com/questions/6014055/how-is-socket-connection-being-handled-in-a-forked-process).

2018-10-16 16:53 UTC, h31 commented on simple_tcp/server_linux/main.c
> +		switch(fork()) {
Обработка нескольких клиентов с помощью `fork` - идея вполне жизнеспособная, но довольно проблематичная. Помимо сложностей с корректным закрытием всех сокетов, вам в курсовом проекте скорее всего понадобится иметь общие (shared) данные для всех клиентов, и на процессах это будет сложнее реализовать. Для первого задания годится, только исправьте проблему с закрытием сокетов.

2018-10-21 21:41 UTC, vana06 commented on simple_tcp/server_linux/main.c
> +	if(setsockopt(sockfd, SOL_SOCKET,(SO_REUSEPORT | SO_REUSEADDR),&(int){ 1 }, sizeof(int)) < 0){
Без SO_REUSEPORT не получается запустить сервер заново. Об опасностях почитал, буду иметь в виду.

2018-11-26 17:17 UTC, h31 commented
Принято.

2018-11-26 17:17 UTC, closed without merging