Task 1
h31/NetworksLab2018 pull request #7
Opened 2018-09-23 10:28 UTC by beloborodova9898

<_>

2018-10-16 17:02 UTC, h31 requested changes

2018-10-16 17:02 UTC, h31 commented on simple_tcp/client_linux/main.c
> +    printf("Please enter the message: ");
Съехало форматирование.

2018-10-16 17:02 UTC, h31 commented on simple_tcp/server_linux/main.c
> +		if (n < 255) break;
Для чего нужно это условие?

2018-10-16 17:02 UTC, h31 commented on simple_tcp/server_linux/main.c
> +	shutdown(newsockfd, 2);
Этого недостаточно для того, чтобы корректно завершить работу сервера. Клиентские сокеты всё ещё остаются открытыми.

2018-10-17 16:52 UTC, beloborodova9898 commented on simple_tcp/server_linux/main.c
> +		if (n < 255) break;
Чтобы понять, когда чтение сообщения закончено. Если считано меньше, чем есть пустого места в буфере, значит следующее считывание не требуется.

2018-11-19 16:46 UTC, h31 approved these changes
Ок, принимаю работу.

2018-11-19 16:46 UTC, h31 commented on simple_tcp/server_linux/main.c
> +	for (; i < max_clients; i = i + 1) {
Обычно цикл `for` пишется по-другому, как `for (int i = 0; i < max_clients; i++)`.

2018-11-19 16:46 UTC, h31 commented on simple_tcp/server_linux/main.c
> +int cliPorts[max_clients];
Не `ports`, а `sockets`.

2018-11-19 16:47 UTC, closed without merging