First task
h31/NetworksLab2018 pull request #8
Opened 2018-09-29 19:01 UTC by staslovelas

2018-10-16 17:09 UTC, h31 requested changes

2018-10-16 17:09 UTC, h31 commented on simple_tcp/client_linux/main.c
> +    char bufforlen[sizeof(long)*8+1];
Для чего нужны эти вычисления?

2018-10-16 17:09 UTC, h31 commented on simple_tcp/client_linux/main.c
> +	shutdown(sockfd, SHUT_RDWR);
Съехало форматирование.

2018-10-16 17:09 UTC, h31 commented on simple_tcp/server_linux/main.c
> +	if(setsockopt(sockfd, SOL_SOCKET, (SO_REUSEPORT | SO_REUSEADDR), & (int) {1}, sizeof(int)) < 0) {
Пожалуйста, пишите, [откуда](https://github.com/h31/NetworksLab2018/pull/4/files#diff-d60665806a7161a7d1d5f9a8ef9c878dR47) берете этот код. И см. замечание по ссылке.

2018-10-16 17:09 UTC, h31 commented on simple_tcp/server_linux/main.c
> +		switch(fork()) {
Во-первых, код взят [отсюда](https://github.com/h31/NetworksLab2018/pull/6/files#diff-d60665806a7161a7d1d5f9a8ef9c878dR70). Списывание в курсе запрещено. См. замечания по ссылке, чем плохо такое решение. Во-вторых, такой большой `switch` банально неудобно читать. Выделяйте большие блоки кода в отдельные функции.

2018-11-10 17:51 UTC, staslovelas commented on simple_tcp/server_linux/main.c
> +		switch(fork()) {
Идея обслуживания нескольких клиентов при помощи fork() взята отсюда: Листинг 6. Эхо сервер:  https://rsdn.org/article/unix/sockets.xml

2018-11-10 18:44 UTC, staslovelas commented on simple_tcp/client_linux/main.c
> +    char bufforlen[sizeof(long)*8+1];
Честно говоря, спустя столько времени я вообще не могу вспомнить, что это за конструкция и какой у нее смысл. Я попробую исправить решение.

2018-11-10 19:12 UTC, staslovelas commented on simple_tcp/server_linux/main.c
> +	if(setsockopt(sockfd, SOL_SOCKET, (SO_REUSEPORT | SO_REUSEADDR), & (int) {1}, sizeof(int)) < 0) {
Да, Вы правы, фрагмент кода заимствован у коллеги Никиты Кузьмина (при его согласии, конечно). Замечание учла.

2018-11-26 17:18 UTC, h31 commented
Принято.

2018-11-26 17:18 UTC, closed without merging